services:
  upcycle-back:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: upcycle-back
    restart: always
    environment:
      - APP_ENV=production
    volumes:
      - /mnt/truenas-web/back/.env.production:/root/.env.production
      - /mnt/truenas-web/back/.env.production:/root/.env.development
      - /mnt/truenas-web/back/images:/root/images
    working_dir: /root
  upcycle-front:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: upcycle-front
    restart: always
    ports:
      - "80:80"
    depends_on:
      - upcycle-back

  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare-tunnel
    restart: always
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    command: tunnel run
    depends_on:
      - upcycle-front
