package seed

var TABLES = []string{
	"finance_settings",
	"accounts",
	"noti_settings",
	"users",
	"employees",
	"pros",
	"events",
	"event_registrations",
	"event_employee",
	"admin_history",
	"posts",
	"comments",
	"saved_posts",
	"viewed_posts",
	"liked_posts",
	"liked_comments",
	"ads",
	"items",
	"project_steps",
	"photos",
	"listings",
	"containers",
	"deposits",
	"barcodes",
	"subscriptions",
	"transactions",
	"step_items",
	"notifications",
	"pro_alert_materials",
}