name: Deploy UpAgain

on:
  push:
    branches:
      - arnaud/ci

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify NAS Access
        run: |
          echo "Checking NAS access..."
          ls -ld /mnt/truenas-web/back/
          ls -ld /mnt/truenas-web/front/
          touch /mnt/truenas-web/back/ci_test && rm /mnt/truenas-web/back/ci_test
          echo "NAS access verified."

      - name: Stop Containers
        run: |
          docker-compose down

      - name: Build Backend
        working-directory: back
        run: |
          /usr/local/go/bin/go build -o api-upagain main.go
          cp api-upagain /mnt/truenas-web/back/
          chmod +x /mnt/truenas-web/back/api-upagain

      - name: Build Frontend
        working-directory: front
        run: |
          npm install
          npm run build
          cp -r dist/* /mnt/truenas-web/front/

      - name: Start Containers
        run: |
          docker-compose up -d

